In [4]:
import numpy as np

In [5]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [6]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [7]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [9]:
data=np.arange(0,9)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
data.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
np.random.rand(25)

array([0.75080633, 0.61092649, 0.73117164, 0.55391909, 0.02313303,
       0.76593455, 0.79502469, 0.33951795, 0.86430406, 0.72374621,
       0.66905702, 0.56396657, 0.085096  , 0.3552238 , 0.05601123,
       0.63865994, 0.56389961, 0.98129378, 0.51241743, 0.27615341,
       0.91745601, 0.00780733, 0.0617981 , 0.03310847, 0.35140699])

In [36]:
arr=np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [28]:
arr[11:25]

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [23]:
arr.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [43]:
arr[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [46]:
arr[3][4]

20

In [47]:
arr.max()

25

In [48]:
arr.min()

1

In [49]:
arr.argmax()

24

In [50]:
arr.argmin()

0

In [57]:
newarr = arr[arr>10]
newarr[newarr<=20]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])